// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnliangcnhtpfgnrrigm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubGlhbmdjbmh0cGZnbnJyaWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjI2MTcsImV4cCI6MjA2NjUzODYxN30.Ty2KyVRzE5fedMFo72b1RFZxP2ShQOauFOrjciAureI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);